name = "equyvo"
compatibility_date = "2026-07-05"
pages_project = "equyvo"

[pages]
build_command = "npm run build:production"
build_output_dir = "dist"

[env.production]
vars = { ENVIRONMENT = "production" }
